// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// *
// Store a record.
type StoreRequest struct {
	Record               *Record  `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}
func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (dst *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(dst, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

// *
// Response to a store record request.
type StoreResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreResponse) Reset()         { *m = StoreResponse{} }
func (m *StoreResponse) String() string { return proto.CompactTextString(m) }
func (*StoreResponse) ProtoMessage()    {}
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}
func (m *StoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreResponse.Unmarshal(m, b)
}
func (m *StoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreResponse.Marshal(b, m, deterministic)
}
func (dst *StoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreResponse.Merge(dst, src)
}
func (m *StoreResponse) XXX_Size() int {
	return xxx_messageInfo_StoreResponse.Size(m)
}
func (m *StoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StoreResponse proto.InternalMessageInfo

// *
// Represents a Record structure with all its necessary information.
type Record struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	MobileNumber         string   `protobuf:"bytes,4,opt,name=MobileNumber,proto3" json:"MobileNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Record) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Record) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Record) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

// *
// Delete a record.
type DeleteRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// *
// Response to delete record request.
type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{4}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StoreRequest)(nil), "dbrpc.StoreRequest")
	proto.RegisterType((*StoreResponse)(nil), "dbrpc.StoreResponse")
	proto.RegisterType((*Record)(nil), "dbrpc.Record")
	proto.RegisterType((*DeleteRequest)(nil), "dbrpc.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "dbrpc.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordsClient is the client API for Records service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordsClient interface {
	// / Store stores a new record if it doesn't already exist. If it does, it updates it.
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// / Delete deletes a record.
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type recordsClient struct {
	cc *grpc.ClientConn
}

func NewRecordsClient(cc *grpc.ClientConn) RecordsClient {
	return &recordsClient{cc}
}

func (c *recordsClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, "/dbrpc.Records/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/dbrpc.Records/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordsServer is the server API for Records service.
type RecordsServer interface {
	// / Store stores a new record if it doesn't already exist. If it does, it updates it.
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// / Delete deletes a record.
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterRecordsServer(s *grpc.Server, srv RecordsServer) {
	s.RegisterService(&_Records_serviceDesc, srv)
}

func _Records_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.Records/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Records_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbrpc.Records/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Records_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbrpc.Records",
	HandlerType: (*RecordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Records_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Records_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4e, 0xc3, 0x30,
	0x10, 0x44, 0x69, 0x68, 0x0c, 0x2c, 0x4d, 0x41, 0x4b, 0x91, 0xac, 0x5e, 0x40, 0x96, 0x90, 0x38,
	0xe5, 0x50, 0x40, 0xfc, 0x40, 0x38, 0xf4, 0x40, 0x0f, 0xe6, 0x0b, 0xea, 0x66, 0x91, 0x2a, 0x25,
	0x38, 0xd8, 0x8e, 0xc4, 0xe7, 0x23, 0xad, 0x1d, 0x44, 0x72, 0xb3, 0xdf, 0xce, 0xd8, 0x33, 0x0b,
	0xe7, 0xb5, 0x29, 0x3b, 0x67, 0x83, 0xc5, 0xbc, 0x36, 0xae, 0x3b, 0xa8, 0x17, 0x58, 0x7c, 0x04,
	0xeb, 0x48, 0xd3, 0x77, 0x4f, 0x3e, 0xe0, 0x03, 0x08, 0x47, 0x07, 0xeb, 0x6a, 0x39, 0xbb, 0x9f,
	0x3d, 0x5e, 0x6e, 0x8a, 0x92, 0x75, 0xa5, 0x66, 0xa8, 0xd3, 0x50, 0x5d, 0x41, 0x91, 0x6c, 0xbe,
	0xb3, 0x5f, 0x9e, 0xd4, 0x27, 0x88, 0x28, 0xc1, 0x25, 0x64, 0xdb, 0x8a, 0xdd, 0x17, 0x3a, 0xdb,
	0x56, 0x88, 0x30, 0xdf, 0xed, 0x5b, 0x92, 0x19, 0x13, 0x3e, 0xe3, 0x0a, 0xf2, 0xb7, 0x76, 0x7f,
	0x6c, 0xe4, 0x29, 0xc3, 0x78, 0x41, 0x05, 0x8b, 0x77, 0x6b, 0x8e, 0x0d, 0xed, 0xfa, 0xd6, 0x90,
	0x93, 0x73, 0x1e, 0x8e, 0x98, 0xba, 0x83, 0xa2, 0xa2, 0x86, 0xc2, 0x5f, 0xe0, 0xc9, 0x77, 0xea,
	0x1a, 0x96, 0x83, 0x20, 0x46, 0xdb, 0xfc, 0xc0, 0x59, 0x8c, 0xe6, 0xf1, 0x19, 0x72, 0x8e, 0x8d,
	0x37, 0xa9, 0xd6, 0xff, 0xee, 0xeb, 0xd5, 0x18, 0xa6, 0x66, 0x27, 0xf8, 0x0a, 0x22, 0x3e, 0x89,
	0x83, 0x62, 0x14, 0x61, 0x7d, 0x3b, 0xa1, 0x83, 0xd1, 0x08, 0x5e, 0xf5, 0xd3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0x6f, 0x46, 0xeb, 0x76, 0x01, 0x00, 0x00,
}
